DROP DATABASE IF EXISTS go;
CREATE DATABASE go;

DROP TABLE IF EXISTS Courses;
DROP TABLE IF EXISTS Coursedata;

\c go;

CREATE TABLE Courses (
    CID SERIAL,
    CNAME VARCHAR(100) PRIMARY KEY
);

CREATE TABLE Coursedata (
    CID Int NOT NULL,
    CNAME VARCHAR(100),
    CPREREQ VARCHAR(100)
);
